#!/usr/bin/env python

import rospy
from nav_msgs.msg import Odometry

# define the callback function for the first car's odom topic
def car1_odom_callback(data):
    rospy.loginfo("Received odom data from car 1: %s", data)

# define the callback function for the second car's odom topic
def car2_odom_callback(data):
    rospy.loginfo("Received odom data from car 2: %s", data)

if __name__ == '__main__':
    # initialize the node
    rospy.init_node('odom_subscriber')
    
    # specify the ROS master URIs of the two cars
    rospy.set_param('limo_base_nodecar1_uri', 'http://<10.0.0.3>:11311')
    rospy.set_param('limo_base_node', 'http://<10.0.0.4>:11311')
    
    # subscribe to the odom topic of the first car
    car1_odom_subscriber = rospy.Subscriber('/limo_base_nodecar1/odom', Odometry, car1_odom_callback)
    
    # subscribe to the odom topic of the second car
    car2_odom_subscriber = rospy.Subscriber('/limo_base_node/odom', Odometry, car2_odom_callback)
    
    # spin the node to keep it running
    rospy.spin()
